### ISSUE TITLE
Configurar o banco de dados

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim_Back-end#4]
### Descrição:

Realizar a modelagem física do banco do dados, utilizando as farramentas escolhidas.

### Tarefas:

- [x] Instalar as bibliotecas necessárias para a criação do banco de dados;
- [x] Criar o banco de dados e testar seu funcionamento;

### Critérios de aceitação:
- [x] Garantir o funcionamento do banco;
- [x] Garantir que cada dev tenha sua propria versão local do banco;

**Comment by eliseukadesh67** [comment]
Tenho uma sugestão de ferramenta para desenvolvermos o banco de dados, e essa ferramente é o [TypeORM](https://typeorm.io/#/). Acredito que essa ferramenta tenha uma sintaxe mais simples, mas é apenas uma questão de gosto pessoal. Sei que as ferramentas ja foram decididas anteriormente, mas como so agora estamos entrando em processo de desenvolvimento de código real, eu pensei nessa sugestão.

Queria a opinião da equipe do backend.

@DanielPortods 
@francisco1code 
@omateusp 
@edsondearaujo
