### ISSUE TITLE
Implementar o sistema de autenticação

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim_Back-end#5]
### Descrição
Issue direcionada para a realização da autenticação do usuário Admin.

### Tarefas
- [x] Definir estrutura de autenticação (JWT, Passport, Cognito e etc);
- [x] Construir middleware para autenticação;
- [x] Construir AuthController para verificar dados de autenticação;
- [x] Fazer INSERT manual no Banco de Dados;

### Critério de aceitação
- [x] O usuário deve efetuar login e logout da aplicação sempre que desejar.

**Comment by edsondearaujo** [comment]
Dei uma olhada em alguns métodos de realizar a autenticação. Pelo que eu entendi a melhor arquitetura seria a JWT, pois é uma estrutura segura e muito usada em  construções de  APIs, já o Passport é mais utilizado em webapp. Deixo aqui alguns links de textos que andei lendo.
- [Passport-local-express](https://github.com/mjhea0/passport-local-express4);
- [bibliotecas de autenticação](https://qastack.com.br/programming/3498005/user-authentication-libraries-for-node-js);
- [JSON Web Token ](https://www.luiztools.com.br/post/autenticacao-json-web-token-jwt-em-nodejs/#1);
-  [Autenticação em Node.js com Passport](https://www.luiztools.com.br/post/autenticacao-em-node-js-com-passport/#2).
